--
-- PostgreSQL database dump
--

\restrict 7pyEdbE2Qnv4iCarkg5K6yTryyepZEIfC3BR5nxRxjHL4zZ9DMFMOC6FAkLQkIY

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255),
    password character varying(255) NOT NULL,
    payment_customer_id character varying(255)
);


--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bed_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bed_type (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: bed_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bed_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bed_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    booking_status character varying(255) NOT NULL,
    check_in_date date,
    check_out_date date,
    created_at timestamp(6) without time zone,
    payment_initiated_at timestamp(6) without time zone,
    reserved_until timestamp(6) without time zone,
    rooms_count integer NOT NULL,
    updated_at timestamp(6) without time zone,
    hotel_id bigint NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT booking_booking_status_check CHECK (((booking_status)::text = ANY ((ARRAY['RESERVED'::character varying, 'GUESTS_ADDED'::character varying, 'PAYMENT_PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: booking_guests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_guests (
    booking_id bigint NOT NULL,
    guest_id bigint NOT NULL
);


--
-- Name: booking_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: guest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guest (
    id bigint NOT NULL,
    age integer NOT NULL,
    gender character varying(255),
    name character varying(255),
    user_id bigint,
    CONSTRAINT guest_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: guest_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: holiday_pricing_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.holiday_pricing_rule (
    id bigint NOT NULL,
    holiday_type character varying(255),
    price_factor numeric(38,2) NOT NULL,
    CONSTRAINT holiday_pricing_rule_holiday_type_check CHECK (((holiday_type)::text = ANY ((ARRAY['NATIONAL'::character varying, 'OPTIONAL'::character varying, 'RELIGIOUS'::character varying, 'LOCAL'::character varying, 'OBSERVANCE'::character varying])::text[])))
);


--
-- Name: holiday_pricing_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.holiday_pricing_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holiday_pricing_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: holidays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.holidays (
    id bigint NOT NULL,
    date date,
    name character varying(255),
    type character varying(255),
    CONSTRAINT holidays_type_check CHECK (((type)::text = ANY ((ARRAY['NATIONAL'::character varying, 'OPTIONAL'::character varying, 'RELIGIOUS'::character varying, 'LOCAL'::character varying, 'OBSERVANCE'::character varying])::text[])))
);


--
-- Name: holidays_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.holidays ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holidays_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotel_min_price; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hotel_min_price (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    date date NOT NULL,
    price numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    hotel_id bigint NOT NULL
);


--
-- Name: hotel_min_price_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hotel_min_price ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hotel_min_price_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotel_pricing_configuration; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hotel_pricing_configuration (
    id bigint NOT NULL,
    occupancy_factor numeric(38,2) NOT NULL,
    occupancy_threshold integer NOT NULL,
    surge_factor numeric(38,2) NOT NULL,
    urgency_days_threshold integer NOT NULL,
    urgency_factor numeric(38,2) NOT NULL,
    owner_id bigint,
    CONSTRAINT hotel_pricing_configuration_occupancy_threshold_check CHECK (((occupancy_threshold >= 50) AND (occupancy_threshold <= 100))),
    CONSTRAINT hotel_pricing_configuration_urgency_days_threshold_check CHECK (((urgency_days_threshold <= 15) AND (urgency_days_threshold >= 1)))
);


--
-- Name: hotel_pricing_configuration_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hotel_pricing_configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hotel_pricing_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hotels (
    id bigint NOT NULL,
    active boolean NOT NULL,
    amenities text[],
    city character varying(255),
    address character varying(255),
    email character varying(255),
    location character varying(255),
    phone_number character varying(255),
    created_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    photos text[],
    updated_at timestamp(6) without time zone,
    owner_id bigint
);


--
-- Name: hotels_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hotels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hotels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory (
    id bigint NOT NULL,
    booked_count integer DEFAULT 0 NOT NULL,
    city character varying(255) NOT NULL,
    closed boolean NOT NULL,
    created_at timestamp(6) without time zone,
    date date NOT NULL,
    dynamic_price numeric(10,2),
    price numeric(10,2) NOT NULL,
    reserved_count integer DEFAULT 0 NOT NULL,
    total_count integer NOT NULL,
    updated_at timestamp(6) without time zone,
    hotel_id bigint NOT NULL,
    room_id bigint NOT NULL
);


--
-- Name: inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    checkout_session_id character varying(255),
    created_at timestamp(6) without time zone,
    payment_intent_id character varying(255),
    payment_status character varying(255) NOT NULL,
    refund_id character varying(255),
    updated_at timestamp(6) without time zone,
    booking_id bigint,
    CONSTRAINT payment_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying, 'REFUND_FAILED'::character varying])::text[])))
);


--
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room (
    id bigint NOT NULL,
    amenities text[],
    base_price numeric(10,2) NOT NULL,
    capacity integer NOT NULL,
    created_at timestamp(6) without time zone,
    photos text[],
    total_count integer NOT NULL,
    updated_at timestamp(6) without time zone,
    bed_type_id bigint NOT NULL,
    hotel_id bigint NOT NULL,
    room_type_id bigint NOT NULL
);


--
-- Name: room_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_type (
    id bigint NOT NULL,
    available boolean NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: room_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    roles character varying(255),
    CONSTRAINT user_roles_roles_check CHECK (((roles)::text = ANY ((ARRAY['GUEST'::character varying, 'HOTEL_MANAGER'::character varying, 'SYSTEM_ADMIN'::character varying])::text[])))
);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: bed_type bed_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bed_type
    ADD CONSTRAINT bed_type_pkey PRIMARY KEY (id);


--
-- Name: booking_guests booking_guests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_guests
    ADD CONSTRAINT booking_guests_pkey PRIMARY KEY (booking_id, guest_id);


--
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: guest guest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guest
    ADD CONSTRAINT guest_pkey PRIMARY KEY (id);


--
-- Name: holiday_pricing_rule holiday_pricing_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holiday_pricing_rule
    ADD CONSTRAINT holiday_pricing_rule_pkey PRIMARY KEY (id);


--
-- Name: holidays holidays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holidays
    ADD CONSTRAINT holidays_pkey PRIMARY KEY (id);


--
-- Name: hotel_min_price hotel_min_price_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotel_min_price
    ADD CONSTRAINT hotel_min_price_pkey PRIMARY KEY (id);


--
-- Name: hotel_pricing_configuration hotel_pricing_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotel_pricing_configuration
    ADD CONSTRAINT hotel_pricing_configuration_pkey PRIMARY KEY (id);


--
-- Name: hotels hotels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotels
    ADD CONSTRAINT hotels_pkey PRIMARY KEY (id);


--
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (id);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- Name: room room_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT room_pkey PRIMARY KEY (id);


--
-- Name: room_type room_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_type
    ADD CONSTRAINT room_type_pkey PRIMARY KEY (id);


--
-- Name: hotel_pricing_configuration uk19t2eonibroafmkl4kv6dxy9x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotel_pricing_configuration
    ADD CONSTRAINT uk19t2eonibroafmkl4kv6dxy9x UNIQUE (owner_id);


--
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- Name: app_user uk20sulhtpppjr6pcei5h0bs3x3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk20sulhtpppjr6pcei5h0bs3x3 UNIQUE (payment_customer_id);


--
-- Name: bed_type uk9lqgaobdiceuorxkuyh7ueb8t; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bed_type
    ADD CONSTRAINT uk9lqgaobdiceuorxkuyh7ueb8t UNIQUE (name);


--
-- Name: payment ukgg60dtb2xi7nyvueligws5d6m; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT ukgg60dtb2xi7nyvueligws5d6m UNIQUE (checkout_session_id);


--
-- Name: payment uknktdkm55por09k8jpf3fcolm6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT uknktdkm55por09k8jpf3fcolm6 UNIQUE (payment_intent_id);


--
-- Name: room_type ukq0y2xl90orh60g19v627mraij; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_type
    ADD CONSTRAINT ukq0y2xl90orh60g19v627mraij UNIQUE (name);


--
-- Name: payment uksb3seo4h1dvmuun2kk2hdo6cp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT uksb3seo4h1dvmuun2kk2hdo6cp UNIQUE (refund_id);


--
-- Name: inventory unique_hotel_room_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT unique_hotel_room_date UNIQUE (hotel_id, room_id, date);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: booking fk1098ar0qrh1i9tes0jkxrw4m1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fk1098ar0qrh1i9tes0jkxrw4m1 FOREIGN KEY (hotel_id) REFERENCES public.hotels(id);


--
-- Name: user_roles fk6fql8djp64yp4q9b3qeyhr82b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk6fql8djp64yp4q9b3qeyhr82b FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: booking_guests fk95khv30phbh2fp6xqdkuh6bmj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_guests
    ADD CONSTRAINT fk95khv30phbh2fp6xqdkuh6bmj FOREIGN KEY (guest_id) REFERENCES public.guest(id);


--
-- Name: room fkd468eq7j1cbue8mk20qfrj5et; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT fkd468eq7j1cbue8mk20qfrj5et FOREIGN KEY (room_type_id) REFERENCES public.room_type(id);


--
-- Name: guest fkdg6lwhvpl89f1yt2i40pbfiiy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guest
    ADD CONSTRAINT fkdg6lwhvpl89f1yt2i40pbfiiy FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: inventory fkj8tchrkcuq572xcpnj6f8vf87; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fkj8tchrkcuq572xcpnj6f8vf87 FOREIGN KEY (hotel_id) REFERENCES public.hotels(id);


--
-- Name: inventory fkkkm00xm4as7hupix7tlg0q3of; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fkkkm00xm4as7hupix7tlg0q3of FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- Name: hotel_min_price fkm9w397hv0cevj65byed3lrbvw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotel_min_price
    ADD CONSTRAINT fkm9w397hv0cevj65byed3lrbvw FOREIGN KEY (hotel_id) REFERENCES public.hotels(id);


--
-- Name: booking_guests fkmn8ku1k7b14s5otjkuteobm1p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_guests
    ADD CONSTRAINT fkmn8ku1k7b14s5otjkuteobm1p FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: hotels fkmuel3fgchpexlmf17u7pewabn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotels
    ADD CONSTRAINT fkmuel3fgchpexlmf17u7pewabn FOREIGN KEY (owner_id) REFERENCES public.app_user(id);


--
-- Name: booking fkn7phgawjwo673xgim9d2cvfe1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkn7phgawjwo673xgim9d2cvfe1 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: booking fkq83pan5xy2a6rn0qsl9bckqai; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkq83pan5xy2a6rn0qsl9bckqai FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- Name: payment fkqewrl4xrv9eiad6eab3aoja65; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkqewrl4xrv9eiad6eab3aoja65 FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: room fkr1kapilxkn8oyx1gr91g6x8cj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT fkr1kapilxkn8oyx1gr91g6x8cj FOREIGN KEY (hotel_id) REFERENCES public.hotels(id);


--
-- Name: hotel_pricing_configuration fkr5fjbu9qn0j9yfvw6i8n06dns; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hotel_pricing_configuration
    ADD CONSTRAINT fkr5fjbu9qn0j9yfvw6i8n06dns FOREIGN KEY (owner_id) REFERENCES public.app_user(id);


--
-- Name: room fkru1ie35g0w6qsg3y90lmypipo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT fkru1ie35g0w6qsg3y90lmypipo FOREIGN KEY (bed_type_id) REFERENCES public.bed_type(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 7pyEdbE2Qnv4iCarkg5K6yTryyepZEIfC3BR5nxRxjHL4zZ9DMFMOC6FAkLQkIY

